# -*- coding: utf-8 -*-
"""🗺 تطبیق نام کشورها بین world-atlas (انگلیسی) و دیتابیس بازی (فارسی)."""

# نام property فایل countries-110m.geojson → نام دقیق در DB (COUNTRIES_LIST)
ATLAS_TO_DB = {
    "Afghanistan": "افغانستان",
    "Albania": "آلبانی",
    "Algeria": "الجزایر",
    "Angola": "آنگولا",
    "Antarctica": "جنوبگان",
    "Argentina": "آرژانتین",
    "Armenia": "ارمنستان",
    "Australia": "استرالیا",
    "Austria": "اتریش",
    "Azerbaijan": "آذربایجان",
    "Bahamas": "باهاما",
    "Bangladesh": "بنگلادش",
    "Belarus": "بلاروس",
    "Belgium": "بلژیک",
    "Belize": "بلیز",
    "Benin": "بنین",
    "Bhutan": "بوتان",
    "Bolivia": "بولیوی",
    "Bosnia and Herz.": "بوسنی و هرزگوین",
    "Botswana": "بوتسوانا",
    "Brazil": "برزیل",
    "Brunei": "برونئی",
    "Bulgaria": "بلغارستان",
    "Burkina Faso": "بورکینافاسو",
    "Burundi": "بروندی",
    "Cambodia": "کامبوج",
    "Cameroon": "کامرون",
    "Canada": "کانادا",
    "Central African Rep.": "آفریقای مرکزی",
    "Chad": "چاد",
    "Chile": "شیلی",
    "China": "چین",
    "Colombia": "کلمبیا",
    "Congo": "کنگو",
    "Costa Rica": "کاستاریکا",
    "Croatia": "کرواسی",
    "Cuba": "کوبا",
    "Cyprus": "قبرس",
    "Czechia": "چک",
    "Côte d'Ivoire": "ساحل عاج",
    "Dem. Rep. Congo": "کنگو دموکراتیک",
    "Denmark": "دانمارک",
    "Djibouti": "جیبوتی",
    "Dominican Rep.": "دومینیکن",
    "Ecuador": "اکوادور",
    "Egypt": "مصر",
    "El Salvador": "السالوادور",
    "Eq. Guinea": "گینه استوایی",
    "Eritrea": "اریتره",
    "Estonia": "استونی",
    "Ethiopia": "اتیوپی",
    "Falkland Is.": "جزایر فالکلند",
    "Fiji": "فیجی",
    "Finland": "فنلاند",
    "Fr. S. Antarctic Lands": "سرزمین‌های جنوبی فرانسه",
    "France": "فرانسه",
    "Gabon": "گابن",
    "Gambia": "گامبیا",
    "Georgia": "گرجستان",
    "Germany": "آلمان",
    "Ghana": "غنا",
    "Greece": "یونان",
    "Greenland": "گرینلند",
    "Guatemala": "گواتمالا",
    "Guinea": "گینه",
    "Guinea-Bissau": "گینه بیسائو",
    "Guyana": "گویان",
    "Haiti": "هائیتی",
    "Honduras": "هندوراس",
    "Hungary": "مجارستان",
    "Iceland": "ایسلند",
    "India": "هند",
    "Indonesia": "اندونزی",
    "Iran": "ایران",
    "Iraq": "عراق",
    "Ireland": "ایرلند",
    "Israel": "اسرائیل",
    "Italy": "ایتالیا",
    "Jamaica": "جامائیکا",
    "Japan": "ژاپن",
    "Jordan": "اردن",
    "Kazakhstan": "قزاقستان",
    "Kenya": "کنیا",
    "Kosovo": "کوزوو",
    "Kuwait": "کویت",
    "Kyrgyzstan": "قرقیزستان",
    "Laos": "لائوس",
    "Latvia": "لتونی",
    "Lebanon": "لبنان",
    "Lesotho": "لسوتو",
    "Liberia": "لیبریا",
    "Libya": "لیبی",
    "Lithuania": "لیتوانی",
    "Luxembourg": "لوکزامبورگ",
    "Macedonia": "مقدونیه شمالی",
    "Madagascar": "ماداگاسکار",
    "Malawi": "مالاوی",
    "Malaysia": "مالزی",
    "Mali": "مالی",
    "Mauritania": "موریتانی",
    "Mexico": "مکزیک",
    "Moldova": "مولداوی",
    "Mongolia": "مغولستان",
    "Montenegro": "مونته‌نگرو",
    "Morocco": "مراکش",
    "Mozambique": "موزامبیک",
    "Myanmar": "میانمار",
    "N. Cyprus": "قبرس شمالی",
    "Namibia": "نامیبیا",
    "Nepal": "نپال",
    "Netherlands": "هلند",
    "New Caledonia": "کالدونیای جدید",
    "New Zealand": "نیوزیلند",
    "Nicaragua": "نیکاراگوئه",
    "Niger": "نیجر",
    "Nigeria": "نیجریه",
    "North Korea": "کره شمالی",
    "Norway": "نروژ",
    "Oman": "عمان",
    "Pakistan": "پاکستان",
    "Palestine": "فلسطین",
    "Panama": "پاناما",
    "Papua New Guinea": "پاپوآ گینه نو",
    "Paraguay": "پاراگوئه",
    "Peru": "پرو",
    "Philippines": "فیلیپین",
    "Poland": "لهستان",
    "Portugal": "پرتغال",
    "Puerto Rico": "پورتوریکو",
    "Qatar": "قطر",
    "Romania": "رومانی",
    "Russia": "روسیه",
    "Rwanda": "رواندا",
    "S. Sudan": "سودان جنوبی",
    "Saudi Arabia": "عربستان",
    "Senegal": "سنگال",
    "Serbia": "صربستان",
    "Sierra Leone": "سیرالئون",
    "Slovakia": "اسلواکی",
    "Slovenia": "اسلوونی",
    "Solomon Is.": "جزایر سلیمان",
    "Somalia": "سومالی",
    "Somaliland": "سومالی‌لند",
    "South Africa": "آفریقای جنوبی",
    "South Korea": "کره جنوبی",
    "Spain": "اسپانیا",
    "Sri Lanka": "سری‌لانکا",
    "Sudan": "سودان",
    "Suriname": "سورینام",
    "Sweden": "سوئد",
    "Switzerland": "سوئیس",
    "Syria": "سوریه",
    "Taiwan": "تایوان",
    "Tajikistan": "تاجیکستان",
    "Tanzania": "تانزانیا",
    "Thailand": "تایلند",
    "Timor-Leste": "تیمور شرقی",
    "Togo": "توگو",
    "Trinidad and Tobago": "ترینیداد و توباگو",
    "Tunisia": "تونس",
    "Turkey": "ترکیه",
    "Turkmenistan": "ترکمنستان",
    "Uganda": "اوگاندا",
    "Ukraine": "اوکراین",
    "United Arab Emirates": "امارات",
    "United Kingdom": "انگلستان",
    "United States of America": "آمریکا",
    "Uruguay": "اروگوئه",
    "Uzbekistan": "ازبکستان",
    "Vanuatu": "وانواتو",
    "Venezuela": "ونزوئلا",
    "Vietnam": "ویتنام",
    "W. Sahara": "صحرای غربی",
    "Yemen": "یمن",
    "Zambia": "زامبیا",
    "Zimbabwe": "زیمبابوه",
    "eSwatini": "اسواتینی",
}
