# Generated by Django 5.0.6 on 2026-09-28 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=32, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('flag', models.CharField(default='🌍', max_length=8)),
                ('neighbors', models.JSONField(blank=True, default=list)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('emoji', models.CharField(default='🏳️', max_length=8)),
                ('population_millions', models.FloatField(default=0)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='core.continent')),
            ],
        ),
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='WarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('credit', models.BigIntegerField(default=10000)),
                ('defense', models.BigIntegerField(default=5000)),
                ('attack_power', models.BigIntegerField(default=0)),
                ('daily_profit', models.BigIntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('population', models.BigIntegerField(default=10000)),
                ('invite_count', models.IntegerField(default=0)),
                ('cabinet', models.JSONField(blank=True, default=dict)),
                ('cabinet_changed', models.BooleanField(default=False)),
                ('active_viruses', models.JSONField(blank=True, default=dict)),
                ('on_fire_until', models.DateTimeField(blank=True, null=True)),
                ('healed_today', models.IntegerField(default=0)),
                ('heal_date', models.CharField(blank=True, default='', max_length=8)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='core.country')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='core.player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=12, unique=True)),
                ('coins', models.BigIntegerField()),
                ('amount_toman', models.BigIntegerField()),
                ('receipt', models.ImageField(upload_to='receipts/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('battle', 'نبرد'), ('bomb', 'بمب'), ('hack', 'هک'), ('assassination', 'ترور'), ('union', 'اتحاد'), ('base', 'پایگاه'), ('virus', 'ویروس'), ('reward', 'جایزه'), ('war', 'جنگ'), ('system', 'سیستم'), ('payment', 'پرداخت'), ('sanction', 'تحریم')], default='system', max_length=16)),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='HackCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hack_type', models.CharField(max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hack_cooldowns', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalBattleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attacker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.player')),
                ('defender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('reason', models.CharField(choices=[('purchase', 'خرید از فروشگاه'), ('daily_profit', 'سود روزانه'), ('battle_loot', 'غنیمت نبرد'), ('battle_loss', 'خسارت نبرد'), ('bomb_loot', 'غنیمت بمب'), ('artillery_win', 'غنیمت توپخانه'), ('artillery_loss', 'خسارت توپخانه'), ('base_build', 'ساخت پایگاه'), ('union_deposit', 'واریز خزانه اتحاد'), ('union_withdraw', 'برداشت خزانه اتحاد'), ('donation_sent', 'اهدای سکه'), ('donation_received', 'دریافت اهدا'), ('referral_bonus', 'جایزه دعوت'), ('admin_grant', 'اهدا ادمین'), ('admin_remove', 'کسر ادمین'), ('toman_purchase', 'خرید تومانی'), ('start_bonus', 'سرمایه شروع'), ('season_reset', 'ریست فصل')], max_length=32)),
                ('balance_after', models.BigIntegerField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='CabinetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_key', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=6)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_codes', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_logs', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='BasePermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('denied', 'رد شده'), ('expired', 'منقضی')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_requests_received', to='core.player')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_requests_sent', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('built_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField()),
                ('ground_troops', models.IntegerField(default=0)),
                ('air_troops', models.IntegerField(default=0)),
                ('max_ground', models.IntegerField(default=5000)),
                ('max_air', models.IntegerField(default=1000)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='core.country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='AttackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_records', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='AssassinationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_key', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=6)),
                ('member_name', models.CharField(blank=True, default='', max_length=64)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('hacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assassination_intel', to='core.player')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaked_codes', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(db_index=True, max_length=64)),
                ('qty', models.BigIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_type', models.CharField(max_length=16)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price_penalty', models.FloatField(default=0.3)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sanction', to='core.player')),
                ('sanctioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_issued', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('score', models.IntegerField(default=0)),
                ('credit', models.BigIntegerField(default=0)),
                ('defense', models.BigIntegerField(default=0)),
                ('attack_power', models.BigIntegerField(default=0)),
                ('population', models.BigIntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_wins', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('statement', 'بیانیه'), ('tweet', 'توییت')], max_length=10)),
                ('text', models.TextField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='StatementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_records', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('union_id', models.CharField(max_length=12, unique=True)),
                ('level', models.IntegerField(default=1)),
                ('treasury', models.BigIntegerField(default=0)),
                ('total_deposits', models.BigIntegerField(default=0)),
                ('total_withdrawals', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_unions', to='core.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_records', to='core.union'),
        ),
        migrations.CreateModel(
            name='UnionDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('credit', 'سکه'), ('item', 'تجهیز')], max_length=6)),
                ('item_key', models.CharField(blank=True, default='', max_length=64)),
                ('qty', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_sent', to='core.player')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_received', to='core.player')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.union')),
            ],
        ),
        migrations.CreateModel(
            name='UnionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.union')),
            ],
        ),
        migrations.AddField(
            model_name='union',
            name='members',
            field=models.ManyToManyField(related_name='unions', through='core.UnionMembership', to='core.player'),
        ),
        migrations.CreateModel(
            name='UnionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('expired', 'منقضی')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.union')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='union_requests', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='UsedCountry',
            fields=[
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reservation', serialize=False, to='core.country')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_countries', to='core.player')),
            ],
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['continent', 'name'], name='core_countr_contine_698cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['player', '-created_at'], name='core_notifi_player__adc92d_idx'),
        ),
        migrations.AddConstraint(
            model_name='hackcooldown',
            constraint=models.UniqueConstraint(fields=('player', 'hack_type'), name='uniq_hack_cooldown'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['player', '-created_at'], name='core_credit_player__014315_idx'),
        ),
        migrations.AddConstraint(
            model_name='cabinetcode',
            constraint=models.UniqueConstraint(fields=('player', 'position_key'), name='uniq_cabinet_code'),
        ),
        migrations.AddIndex(
            model_name='battlelog',
            index=models.Index(fields=['player', '-ts'], name='core_battle_player__315a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='base',
            index=models.Index(fields=['owner'], name='core_base_owner_i_294925_idx'),
        ),
        migrations.AddIndex(
            model_name='base',
            index=models.Index(fields=['country'], name='core_base_country_d83c43_idx'),
        ),
        migrations.AddIndex(
            model_name='attackrecord',
            index=models.Index(fields=['player', 'at'], name='core_attack_player__43d096_idx'),
        ),
        migrations.AddConstraint(
            model_name='assassinationinfo',
            constraint=models.UniqueConstraint(fields=('hacker', 'target', 'position_key'), name='uniq_assass_intel'),
        ),
        migrations.AddIndex(
            model_name='playeritem',
            index=models.Index(fields=['player', 'item_key'], name='core_player_player__46a831_idx'),
        ),
        migrations.AddConstraint(
            model_name='playeritem',
            constraint=models.UniqueConstraint(fields=('player', 'item_key'), name='uniq_player_item'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['-created_at'], name='core_statem_created_327745_idx'),
        ),
        migrations.AddIndex(
            model_name='statementrecord',
            index=models.Index(fields=['player', 'at'], name='core_statem_player__b66c60_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['-score'], name='core_player_score_8c2cae_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['country'], name='core_player_country_c47f4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='unionmembership',
            constraint=models.UniqueConstraint(fields=('player', 'union'), name='uniq_union_member'),
        ),
        migrations.AddIndex(
            model_name='union',
            index=models.Index(fields=['-treasury'], name='core_union_treasur_296b94_idx'),
        ),
        migrations.AddIndex(
            model_name='usedcountry',
            index=models.Index(fields=['player'], name='core_usedco_player__3e544d_idx'),
        ),
    ]
