# Generated by Django 5.0.6 on 2026-09-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='reason',
            field=models.CharField(choices=[('purchase', 'خرید از فروشگاه'), ('daily_profit', 'سود روزانه'), ('battle_loot', 'غنیمت نبرد'), ('battle_loss', 'خسارت نبرد'), ('bomb_loot', 'غنیمت بمب'), ('artillery_win', 'غنیمت توپخانه'), ('artillery_loss', 'خسارت توپخانه'), ('base_build', 'ساخت پایگاه'), ('union_deposit', 'واریز خزانه اتحاد'), ('union_withdraw', 'برداشت خزانه اتحاد'), ('donation_sent', 'اهدای سکه'), ('donation_received', 'دریافت اهدا'), ('referral_bonus', 'جایزه دعوت'), ('admin_grant', 'اهدا ادمین'), ('admin_remove', 'کسر ادمین'), ('toman_purchase', 'خرید تومانی'), ('start_bonus', 'سرمایه شروع'), ('season_reset', 'ریست فصل'), ('achievement_reward', 'جایزه دستاورد')], max_length=32),
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_key', models.CharField(max_length=64)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player'], name='core_player_player__13acf0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='playerachievement',
            constraint=models.UniqueConstraint(fields=('player', 'achievement_key'), name='uniq_player_achievement'),
        ),
    ]
