# Generated by Django 5.0.6 on 2026-09-28 21:39

import core.models_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_credittransaction_reason_playerachievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingpayment',
            name='receipt',
            field=models.ImageField(upload_to=core.models_base._receipt_upload_to),
        ),
    ]
