# Generated by Django 5.0.6 on 2026-09-28 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pendingpayment_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ban_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='privacy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('register', 'ثبت\u200cنام'), ('login', 'ورود'), ('battle_start', 'شروع نبرد'), ('battle_end', 'پایان نبرد'), ('alliance_created', 'ساخت اتحاد'), ('large_transaction', 'تراکنش بزرگ'), ('suspicious', 'فعالیت مشکوک'), ('admin_action', 'اکشن ادمین'), ('system_warning', 'هشدار سیستم'), ('achievement', 'دستاورد'), ('base_built', 'ساخت پایگاه'), ('union_join', 'عضویت در اتحاد')], max_length=24)),
                ('actor_name', models.CharField(blank=True, default='', max_length=32)),
                ('text', models.CharField(max_length=256)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_kind', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.player')),
            ],
            options={
                'indexes': [models.Index(fields=['-created_at'], name='core_activi_created_3d0bd9_idx'), models.Index(fields=['kind'], name='core_activi_kind_6d3c38_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, default='', max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('target', models.CharField(blank=True, default='', max_length=128)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['-created_at'], name='core_admina_created_a4a3de_idx')],
            },
        ),
    ]
