# Generated by Django 5.0.6 on 2026-09-28 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_ban_reason_player_banned_at_player_last_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ships', models.JSONField(default=dict)),
                ('ships_left', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('outbound', 'در مسیر'), ('returning', 'بازگشت'), ('done', 'انجام شد')], default='outbound', max_length=12)),
                ('departed_at', models.DateTimeField()),
                ('arrive_at', models.DateTimeField()),
                ('return_at', models.DateTimeField(blank=True, null=True)),
                ('loot', models.BigIntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_origins', to='core.country')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_missions', to='core.player')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleets_incoming', to='core.player')),
                ('target_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_targets', to='core.country')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'arrive_at'], name='core_fleetm_status_901554_idx'), models.Index(fields=['player', '-created_at'], name='core_fleetm_player__e0c88e_idx')],
            },
        ),
    ]
