# Generated by Django 5.0.6 on 2026-09-28 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fleetmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=64)),
                ('suffix', models.CharField(default='count', max_length=32)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='core.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'item_key'], name='core_placem_player__38621d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='placement',
            constraint=models.UniqueConstraint(fields=('player', 'item_key', 'suffix', 'lat', 'lon'), name='uniq_player_placement'),
        ),
    ]
