# Generated by Django 5.0.6 on 2026-09-29 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_placement_placement_uniq_player_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=64)),
                ('flag_emoji', models.CharField(blank=True, default='', max_length=8)),
                ('map_color', models.CharField(blank=True, default='', max_length=9)),
                ('capital_name', models.CharField(blank=True, default='', max_length=64)),
                ('capital_lat', models.FloatField(blank=True, null=True)),
                ('capital_lon', models.FloatField(blank=True, null=True)),
                ('government', models.CharField(blank=True, default='', max_length=32)),
                ('imaginary', models.BooleanField(default=False)),
                ('divisions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.country')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_profiles', to='core.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player'], name='core_countr_player__d7372f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='countryprofile',
            constraint=models.UniqueConstraint(fields=('player', 'country'), name='uniq_player_country_profile'),
        ),
    ]
