# Generated by Django 5.0.6 on 2026-09-29 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_countryprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akey', models.CharField(blank=True, max_length=80, unique=True)),
                ('type', models.CharField(choices=[('non_aggression', 'پیمان عدم تجاوز'), ('alliance', 'اتحاد نظامی'), ('transit', 'توافق ترانزیت'), ('trade', 'توافق تجاری')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('terminated', 'خاتمه\u200cیافته'), ('expired', 'منقضی')], default='active', max_length=12)),
                ('terms', models.JSONField(blank=True, default=dict)),
                ('deliveries_done', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements_init', to='core.country')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements_part', to='core.country')),
            ],
            options={
                'indexes': [models.Index(fields=['initiator', 'status'], name='core_agreem_initiat_edc055_idx'), models.Index(fields=['partner', 'status'], name='core_agreem_partner_369b4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akey', models.CharField(db_index=True, max_length=120)),
                ('type', models.CharField(choices=[('resource_shortage', 'کمبود منابع'), ('treasury_low', 'خزانه کم'), ('supply_disruption', 'اختلال تأمین'), ('equipment_shortage', 'کمبود تجهیزات'), ('military_readiness', 'آمادگی نظامی'), ('production_failure', 'شکست تولید'), ('diplomatic_change', 'تغییر دیپلماتیک'), ('trade_disruption', 'اختلال تجارت'), ('infrastructure_capacity', 'ظرفیت زیرساخت'), ('construction_delay', 'تأخیر ساخت')], max_length=28)),
                ('severity', models.CharField(choices=[('critical', 'بحرانی'), ('warning', 'هشدار'), ('info', 'اطلاع')], default='warning', max_length=10)),
                ('priority', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('cause', models.CharField(blank=True, default='', max_length=256)),
                ('recommended_action', models.CharField(blank=True, default='', max_length=256)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('acknowledged', 'تأیید\u200cشده'), ('resolved', 'حل\u200cشده')], default='active', max_length=12)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.country')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'status'], name='core_alert_player__509a26_idx'), models.Index(fields=['-priority'], name='core_alert_priorit_d6887b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiplomaticProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akey', models.CharField(blank=True, max_length=80, unique=True)),
                ('type', models.CharField(choices=[('non_aggression', 'پیمان عدم تجاوز'), ('alliance', 'اتحاد نظامی'), ('transit', 'توافق ترانزیت'), ('trade', 'توافق تجاری')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'ارسال\u200cشده'), ('pending', 'در انتظار پاسخ'), ('accepted', 'پذیرفته\u200cشده'), ('rejected', 'رد\u200cشده'), ('expired', 'منقضی'), ('cancelled', 'لغوشده')], default='pending', max_length=12)),
                ('terms', models.JSONField(blank=True, default=dict)),
                ('counter_terms', models.JSONField(blank=True, null=True)),
                ('ai_review', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('from_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_out', to='core.country')),
                ('to_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_in', to='core.country')),
            ],
            options={
                'indexes': [models.Index(fields=['to_country', 'status'], name='core_diplom_to_coun_14ae60_idx'), models.Index(fields=['-created_at'], name='core_diplom_created_bb5db1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiplomaticRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_score', models.IntegerField(default=0)),
                ('trust', models.IntegerField(default=0)),
                ('tension', models.IntegerField(default=0)),
                ('last_interaction_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_out', to='core.country')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_in', to='core.country')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'relation_score'], name='core_diplom_source__07c3a0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='diplomaticrelation',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='uniq_diplo_pair'),
        ),
    ]
